# Generated by Django 2.0 on 2020-09-12 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serverapp', '0002_address_info'),
    ]

    operations = [
        migrations.DeleteModel(
            name='address_info',
        ),
        migrations.RemoveField(
            model_name='temp',
            name='recv',
        ),
        migrations.RemoveField(
            model_name='temp',
            name='send',
        ),
        migrations.AddField(
            model_name='temp',
            name='position',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='temp',
            name='temperature',
            field=models.FloatField(default=0),
        ),
    ]
