# Generated by Django 2.0 on 2020-09-16 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serverapp', '0003_auto_20200912_2218'),
    ]

    operations = [
        migrations.CreateModel(
            name='temp2',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('position', models.FloatField(default=0)),
                ('temperature', models.FloatField(default=0)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RenameModel(
            old_name='temp',
            new_name='temp1',
        ),
    ]
